version: "3.2"
services:
  flask:
    build:
      dockerfile: Dockerfile1
      context: .
    command: python run.py
    volumes:
      - ./src:/usr/src/app/

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
